// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/tools/list-entrepreneurs.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z } from "npm:zod@^4.4.3";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.97.0";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error(
    "SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required"
  );
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/list-entrepreneurs.ts
var list_entrepreneurs_default = defineTool({
  name: "list_entrepreneurs",
  title: "List entrepreneurs",
  description: "List entrepreneurs in the Grow Movement platform, optionally filtered by country, sector, status or a free-text search on name/business.",
  inputSchema: {
    search: z.string().optional().describe("Free-text match on entrepreneur or business name."),
    country: z.string().optional().describe("Filter by country."),
    sector: z.string().optional().describe("Filter by sector."),
    status: z.string().optional().describe("Filter by status, e.g. Active or Seed Fund Candidate."),
    limit: z.number().int().optional().describe("Max rows to return (default 25, max 100).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ search, country, sector, status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const take = Math.min(Math.max(limit ?? 25, 1), 100);
    let query = supabaseForUser(ctx).from("entrepreneurs").select(
      "id, name, business_name, country, sector, stage, status, program_id, pitch_summary, updated_at"
    ).order("updated_at", { ascending: false }).limit(take);
    if (country) query = query.ilike("country", country);
    if (sector) query = query.ilike("sector", sector);
    if (status) query = query.eq("status", status);
    if (search) query = query.or(`name.ilike.%${search}%,business_name.ilike.%${search}%`);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { count: data?.length ?? 0, entrepreneurs: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-entrepreneur.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z2 } from "npm:zod@^4.4.3";
var get_entrepreneur_default = defineTool2({
  name: "get_entrepreneur",
  title: "Get entrepreneur",
  description: "Get the full profile of one entrepreneur by id, including business details, challenges, funding needs and impact.",
  inputSchema: {
    id: z2.string().describe("Entrepreneur id (uuid).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser(ctx).from("entrepreneurs").select("*").eq("id", id).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) {
      return {
        content: [{ type: "text", text: `No entrepreneur found with id ${id}` }],
        isError: true
      };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { entrepreneur: data }
    };
  }
});

// src/lib/mcp/tools/list-programs.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z3 } from "npm:zod@^4.4.3";
var list_programs_default = defineTool3({
  name: "list_programs",
  title: "List programs",
  description: "List Grow Movement coaching programs with their status and description.",
  inputSchema: {
    status: z3.string().optional().describe("Filter by program status.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    let query = supabaseForUser(ctx).from("programs").select("id, name, description, status, created_at, updated_at").order("created_at", { ascending: false });
    if (status) query = query.eq("status", status);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { count: data?.length ?? 0, programs: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-projects.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z4 } from "npm:zod@^4.4.3";
var list_projects_default = defineTool4({
  name: "list_projects",
  title: "List projects",
  description: "List coaching projects, optionally filtered by program, status, coach or entrepreneur. Use this to see active engagements.",
  inputSchema: {
    program_id: z4.string().optional().describe("Filter by program id (uuid)."),
    status: z4.string().optional().describe("Filter by project status."),
    coach_id: z4.string().optional().describe("Filter by coach id (uuid)."),
    entrepreneur_id: z4.string().optional().describe("Filter by entrepreneur id (uuid)."),
    limit: z4.number().int().optional().describe("Max rows to return (default 25, max 100).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ program_id, status, coach_id, entrepreneur_id, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const take = Math.min(Math.max(limit ?? 25, 1), 100);
    let query = supabaseForUser(ctx).from("projects").select(
      "id, name, description, status, program_id, coach_id, entrepreneur_id, match_id, created_at, updated_at"
    ).order("updated_at", { ascending: false }).limit(take);
    if (program_id) query = query.eq("program_id", program_id);
    if (status) query = query.eq("status", status);
    if (coach_id) query = query.eq("coach_id", coach_id);
    if (entrepreneur_id) query = query.eq("entrepreneur_id", entrepreneur_id);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { count: data?.length ?? 0, projects: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-matching-requests.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z5 } from "npm:zod@^4.4.3";
var list_matching_requests_default = defineTool5({
  name: "list_matching_requests",
  title: "List matching requests",
  description: "List incoming coach/entrepreneur matching requests submitted through the website, newest first.",
  inputSchema: {
    status: z5.string().optional().describe("Filter by request status."),
    limit: z5.number().int().optional().describe("Max rows to return (default 25, max 100).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const take = Math.min(Math.max(limit ?? 25, 1), 100);
    let query = supabaseForUser(ctx).from("matching_requests").select(
      "id, requester_name, requester_email, requester_organization, requester_role, status, support_description, message, created_at"
    ).order("created_at", { ascending: false }).limit(take);
    if (status) query = query.eq("status", status);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { count: data?.length ?? 0, requests: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/add-project-note.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z6 } from "npm:zod@^4.4.3";
var add_project_note_default = defineTool6({
  name: "add_project_note",
  title: "Add project note",
  description: "Add a progress/tracking note to a coaching project. The note is recorded against the signed-in user.",
  inputSchema: {
    project_id: z6.string().describe("Project id (uuid) to attach the note to."),
    note: z6.string().trim().describe("The note text.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ project_id, note }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    if (!note) {
      return { content: [{ type: "text", text: "Note text is required" }], isError: true };
    }
    const { data, error } = await supabaseForUser(ctx).from("project_track_notes").insert({ project_id, note, author_id: ctx.getUserId() }).select("id, project_id, note, created_at").maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Note added to project ${project_id}.` }],
      structuredContent: { note: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "ltndicrqlqaudtlvcklh";
var mcp_default = defineMcp({
  name: "grow-movement-app",
  title: "Grow Movement App",
  version: "0.1.0",
  instructions: "Tools for the Grow Movement platform. Read entrepreneurs, programs, coaching projects and matching requests, and add progress notes to projects. All calls run as the signed-in Grow Movement user, so results respect that user's access.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    list_entrepreneurs_default,
    get_entrepreneur_default,
    list_programs_default,
    list_projects_default,
    list_matching_requests_default,
    add_project_note_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
